### ISSUE TITLE
[Questsion] Renovate-pro does not rebase PR on demand 

### ISSUE THREAD

**Issue by huydinhle** [renovatebot/pro#83]
After upgraded to the latest 0.18.0 renovate( including removing the postgres in our deployment), we notice that renovate-pro doesn't really rebase our PR on demand after it started for like 30 minutes. We would see the rebase-request enqueue, but then renovate would not consume that queue item.

We delete the renovate-pro pod to see if it solves the problem, and renovate seems to be responsive again to rebase our PR but after 15 to 30 minutes, the same problem persist.

Is there a way for us to test/debug this problem?

**Comment by rarkins** [comment]
Do your logs show if Renovate is processing *other* jobs? Eg it should have scheduled jobs hourly.

**Comment by huydinhle** [comment]
yes, it does.

**Comment by wyardley** [comment]
If it's relevant, we also have a lot of repos, but they're almost entirely scheduled to only actually run (based on their Renovate config) overnight. That said, we do see Renovate chugging through them all the time, even though they're not within schedule; my understanding is that the manual rebase requests are supposed to be with highest priority, though? in the past, they've been pretty responsive.

**Comment by rarkins** [comment]
It's expected that Renovate will still check repositories hourly despite scheduling. For example if an unscheduled branch becomes conflicted then Renovate will rebase it to fix that.

And yes, manual rebase requests are supposed to have highest priority. Maybe somehow that's not happening, i.e. they're being put to the back of the queue instead of front.

**Comment by rarkins** [comment]
I've published renovate/pro:0.18.1 just now to add extra logging to job queue operations. No other changes have been made to affect functionality (e.g. there's no upgrade of the core Renovate version). Ideally run it at LOG_LEVEL=debug and then look for all log messages starting with 'Job queue:', e.g.

```
server_1  | DEBUG: Job queue: returning next job
server_1  |        "job": {
server_1  |          "reason": "scheduled",
server_1  |          "repository": "my/repo",
server_1  |          "priority": 100,
server_1  |          "installationId": 1312179
server_1  |        }
```

**Comment by huydinhle** [comment]
will test this out and get back. Thank you so much @rarkins

**Comment by huydinhle** [comment]
so after I deleted the renovate-pro pod, the rebase request starts to work pretty quickly right after I clicked the checklist. But After 2 or 3 hours, rebase request get super slow again. Here is what I found in the logs whenever an on-demand rebase request happens with our renovate-pro
```
DEBUG: Job queue: enqueing job (repository=honeyscience/honey-lending-transactions)
       "reason": "rebase-request",
       "priority": 15
DEBUG: Job queue: Existing job found for repository (repository=honeyscience/honey-lending-transactions)
DEBUG: Job queue: Existing job does not need priority bump (repository=honeyscience/honey-lending-transactions)
       "existingPriority": 15,
       "priority": 15
DEBUG: Received webhook event (repository=honeyscience/honey-lending-transactions)
       "event": "status",
       "action": undefined,
       "installationId": 1227754
DEBUG: Ignoring event type: status (repository=honeyscience/honey-lending-transactions)
DEBUG: Received webhook event (repository=honeyscience/honey-lending-transactions)
       "event": "status",
       "action": undefined,
       "installationId": 1227754
DEBUG: Ignoring event type: status (repository=honeyscience/honey-lending-transactions)
```

**Comment by rarkins** [comment]
This log confirms that:
- the event is detected correctly
- the repository already had a job in the queue, with same priority. i.e. another rebase request

I usually wouldn't expect to see two jobs unless you unticked the checkbox and then ticked it again, or did some other edit? But it probably doesn't matter.

What I'm interested in is whether Pro is processing other jobs at the same time. e.g. if you capture logs for longer then do you see messages indicating the start of a more jobs? If Pro is somehow "blocked" then it won't matter what's in the queue because the queue isn't being processed.

**Comment by huydinhle** [comment]
@rarkins . Is there a way to know if pro is somehow "blocked".  Pro is definitely processing other jobs at the same time. The logs does indicate that pro is enqueuing more jobs and processing more jobs. However, the rebase has the priority of 15 which is pretty high. When I look at  logs after I put in a rebase request, all the later jobs have priority of 40 and above. So I still don't know how rebase not getting processed right away. 

If rebase doesn't get processed right away, when is the next time that pro will process these rebase 
request? Or in general, how does a rebase request( or an item with priority of 15) get processed?

Is there any debug endpoint or a way to show what is in the queue?

**Comment by rarkins** [comment]
I'll put out a new release next week that lets you debug the queue via API. Potentially we have a sorting problem too, so I'll try to inspect the code for any problems.

**Comment by huydinhle** [comment]
@rarkins Awesome!. thank you. Look forward for that next release

**Comment by rarkins** [comment]
Hi, I located the bug responsible for this behaviour. Please see [Release 0.18.3](https://github.com/renovatebot/pro/releases/tag/0.18.3)

**Comment by wyardley** [comment]
Thanks!
